### ISSUE TITLE
URL正規化Helper の作成

### ISSUE THREAD

**Issue by hata6502** [blue-hood/apps#1]
MiddleWare でリダイレクトに使うほか、内部リンクの正規化にも使用する。

**Comment by hata6502** [comment]
http -> https 置換。

**Comment by Hato6502** [comment]
クエリ中の%20 -> + (nginx)
末尾の / (nginx)
index.* (nginx)
クエリの順番ソート (laravel)
//... -> / (nginx)
末尾の? を消す。 (nginx)
http -> https (nginx)

301 permanent で。
